# Generated by Django 3.0 on 2024-04-19 06:53

from django.db import migrations, models
import django.db.models.deletion
import forums.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500, unique=True)),
                ('posted_on', models.DateTimeField()),
                ('description', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to=forums.models.get_upload_path_question)),
                ('score', models.IntegerField(default=0)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField()),
                ('answer', models.TextField(default='')),
                ('answer_files', models.FileField(blank=True, null=True, upload_to=forums.models.get_upload_path_answer)),
                ('score', models.IntegerField(default=0)),
                ('answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teams')),
                ('answer_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Threads')),
            ],
        ),
    ]
